name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      continue-on-error: true
      run: cargo clippy --all-targets --all-features --verbose -- -D warnings
    - name: Rustfmt
      continue-on-error: true
      run: cargo fmt --check --verbose
    - name: Run tests
      run: cargo test --verbose
